# Libraries required for EDA
## pandas
## numpy
## matplotlib
## seaborn

In [3]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [4]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Step 1 -- Importing data

In [40]:
df=pd.read_csv("/content/drive/MyDrive/Videos PPT/brain_stroke.csv")

In [41]:
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
4976,Male,41.0,0,0,No,Private,Rural,70.15,29.8,formerly smoked,0
4977,Male,40.0,0,0,Yes,Private,Urban,191.15,31.1,smokes,0
4978,Female,45.0,1,0,Yes,Govt_job,Rural,95.02,31.8,smokes,0
4979,Male,40.0,0,0,Yes,Private,Rural,83.94,30.0,smokes,0
4980,Female,80.0,1,0,Yes,Private,Urban,83.75,29.1,never smoked,0

# Step 2 -- Get Insight of data 
## Basic EDA

In [7]:
df.shape

(4981, 11)

In [8]:
df.head()

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,67.0,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,80.0,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,49.0,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,79.0,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,81.0,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1

In [9]:
df.columns

Index(['gender', 'age', 'hypertension', 'heart_disease', 'ever_married',
       'work_type', 'Residence_type', 'avg_glucose_level', 'bmi',
       'smoking_status', 'stroke'],
      dtype='object')

In [12]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4981 entries, 0 to 4980
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   gender             4981 non-null   object
 1   age                4981 non-null   float64
 2   hypertension       4981 non-null   int64
 3   heart_disease      4981 non-null   int64
 4   ever_married       4981 non-null   object
 5   work_type          4981 non-null   object
 6   Residence_type     4981 non-null   object
 7   avg_glucose_level  4981 non-null   float64
 8   bmi                4981 non-null   float64
 9   smoking_status     4981 non-null   object
 10  stroke             4981 non-null   int64
dtypes: float64(3), int64(3), object(5)
memory usage: 428.2+ KB

In [11]:
df.describe()

,age,hypertension,heart_disease,avg_glucose_level,bmi,stroke
count,4981.000000,4981.000000,4981.000000,4981.000000,4981.000000,4981.000000
mean,43.419859,0.096165,0.055210,105.943562,28.498173,0.049789
std,22.662755,0.294848,0.228412,45.075373,6.790464,0.217531
min,0.080000,0.000000,0.000000,55.120000,14.000000,0.000000
25%,25.000000,0.000000,0.000000,77.230000,23.700000,0.000000
50%,45.000000,0.000000,0.000000,91.850000,28.100000,0.000000
75%,61.000000,0.000000,0.000000,113.860000,32.600000,0.000000
max,82.000000,1.000000,1.000000,271.740000,48.900000,1.000000

In [13]:
 df.groupby("work_type")["stroke"].count().reset_index()

       work_type  stroke
0       Govt_job     644
1        Private    2860
2  Self-employed     804
3       children     673

In [14]:
df["bmi"].unique()

array([36.6, 32.5, 34.4, 24. , 29. , 27.4, 22.8, 24.2, 29.7, 36.8, 27.3,
       28.2, 30.9, 37.5, 25.8, 37.8, 22.4, 48.9, 26.6, 27.2, 23.5, 28.3,
       44.2, 25.4, 22.2, 30.5, 26.5, 33.7, 23.1, 32. , 29.9, 23.9, 28.5,
       26.4, 20.2, 33.6, 38.6, 39.2, 27.7, 31.4, 36.5, 33.2, 32.8, 40.4,
       25.3, 30.2, 47.5, 20.3, 30. , 28.9, 28.1, 31.1, 21.7, 27. , 24.1,
       45.9, 44.1, 22.9, 29.1, 32.3, 41.1, 25.6, 29.8, 26.3, 26.2, 29.4,
       24.4, 28. , 28.8, 34.6, 19.4, 30.3, 41.5, 22.6, 27.1, 31.3, 31. ,
       31.7, 35.8, 28.4, 20.1, 26.7, 38.7, 34.9, 25. , 23.8, 21.8, 27.5,
       24.6, 32.9, 26.1, 31.9, 34.1, 36.9, 37.3, 45.7, 34.2, 23.6, 22.3,
       37.1, 45. , 25.5, 30.8, 37.4, 34.5, 27.9, 29.5, 46. , 42.5, 35.5,
       26.9, 45.5, 31.5, 33. , 23.4, 30.7, 20.5, 21.5, 40. , 28.6, 42.2,
       29.6, 35.4, 16.9, 26.8, 39.3, 32.6, 35.9, 21.2, 42.4, 40.5, 36.7,
       29.3, 19.6, 18. , 17.6, 17.7, 35. , 22. , 39.4, 19.7, 22.5, 25.2,
       41.8, 23.7, 24.5, 31.2, 16. , 31.6, 25.1, 24.8, 18.3, 20. , 19.5,
       36. , 35.3, 40.1, 43.1, 21.4, 34.3, 27.6, 16.5, 24.3, 25.7, 21.9,
       38.4, 25.9, 18.6, 24.9, 48.2, 20.7, 39.5, 23.3, 35.1, 43.6, 21. ,
       47.3, 16.6, 21.6, 15.5, 35.6, 16.7, 41.9, 16.4, 17.1, 29.2, 37.9,
       44.6, 39.6, 40.3, 41.6, 39. , 23.2, 18.9, 36.1, 36.3, 46.5, 16.8,
       46.6, 35.2, 20.9, 31.8, 15.3, 38.2, 45.2, 17. , 27.8, 23. , 22.1,
       26. , 44.3, 39.7, 34.7, 21.3, 41.2, 34.8, 19.2, 35.7, 40.8, 24.7,
       19. , 32.4, 34. , 28.7, 32.1, 20.4, 30.6, 19.3, 40.9, 17.2, 16.1,
       16.2, 40.6, 18.4, 21.1, 42.3, 32.2, 17.5, 42.1, 47.8, 20.8, 30.1,
       17.3, 36.4, 36.2, 14.4, 43. , 41.7, 33.8, 43.9, 22.7, 18.7, 37. ,
       38.5, 16.3, 44. , 32.7, 40.2, 33.3, 17.4, 41.3, 14.6, 17.8, 46.1,
       33.1, 18.1, 43.8, 38.9, 43.7, 39.9, 15.9, 19.8, 38.3, 41. , 42.6,
       43.4, 15.1, 20.6, 33.5, 43.2, 19.1, 30.4, 38. , 33.4, 44.9, 44.7,
       37.6, 39.8, 42. , 37.2, 42.8, 18.8, 42.9, 14.3, 37.7, 48.4, 46.2,
       43.3, 33.9, 18.5, 44.5, 45.4, 19.9, 17.9, 15.6, 15.2, 18.2, 48.5,
       14.1, 15.7, 44.8, 38.1, 44.4, 38.8, 39.1, 41.4, 14.2, 15.4, 45.1,
       48.7, 42.7, 48.8, 15.8, 45.3, 14.8, 40.7, 48. , 46.8, 48.3, 14.5,
       15. , 47.4, 47.9, 45.8, 47.6, 14. , 46.4, 46.9, 47.1, 48.1, 46.3,
       14.9])

In [20]:
df.groupby("smoking_status")["hypertension"].mean().reset_index()

    smoking_status  hypertension
0          Unknown      0.033333
1  formerly smoked      0.132641
2     never smoked      0.121328
3           smokes      0.117268

In [33]:
df.groupby(["smoking_status","work_type"]).agg({"hypertension":"mean","avg_glucose_level":["min","max"]}).reset_index()

     smoking_status      work_type hypertension avg_glucose_level
                                           mean               min     max
0           Unknown       Govt_job     0.025000             56.08  226.28
1           Unknown        Private     0.044944             55.26  260.85
2           Unknown  Self-employed     0.124183             55.23  230.68
3           Unknown       children     0.000000             55.34  219.81
4   formerly smoked       Govt_job     0.145038             55.27  255.17
5   formerly smoked        Private     0.117534             56.11  267.76
6   formerly smoked  Self-employed     0.171569             56.08  261.67
7   formerly smoked       children     0.000000             63.22  144.08
8      never smoked       Govt_job     0.116788             55.84  266.59
9      never smoked        Private     0.107083             55.12  267.60
10     never smoked  Self-employed     0.197531             55.46  251.60
11     never smoked       children     0.000000             57.28  213.87
12           smokes       Govt_job     0.134454             55.47  229.86
13           smokes        Private     0.105263             55.34  271.74
14           smokes  Self-employed     0.154472             55.32  267.61
15           smokes       children     0.000000             63.08  207.45

In [28]:
df.sort_values(by=['bmi','avg_glucose_level'],ascending=[True,True]).head(20)

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
4223,Female,4.00,0,0,No,children,Urban,94.27,14.0,Unknown,0
1776,Female,67.00,0,0,Yes,Private,Urban,82.09,14.1,never smoked,0
2609,Female,8.00,0,0,No,children,Rural,87.92,14.1,Unknown,0
3193,Male,0.56,0,0,No,children,Urban,98.23,14.1,Unknown,0
3907,Female,3.00,0,0,No,children,Rural,131.81,14.1,Unknown,0
1487,Female,0.08,0,0,No,children,Urban,139.67,14.1,Unknown,0
3148,Male,0.24,0,0,No,children,Urban,89.28,14.2,Unknown,0
3939,Female,3.00,0,0,No,children,Rural,108.32,14.2,Unknown,0
2052,Male,2.00,0,0,No,children,Rural,112.66,14.2,Unknown,0
2468,Male,61.00,0,0,Yes,Private,Urban,227.98,14.2,Unknown,0
2682,Male,10.00,0,0,No,children,Urban,87.09,14.3,Unknown,0
1474,Male,0.40,0,0,No,children,Urban,109.56,14.3,Unknown,0
1081,Female,11.00,0,0,No,children,Rural,122.75,14.3,Unknown,0
3277,Female,11.00,0,0,No,children,Urban,69.68,14.4,Unknown,0
615,Female,1.80,0,0,No,children,Urban,130.61,14.4,Unknown,0
3083,Female,9.00,0,0,No,children,Urban,82.64,14.5,Unknown,0
3368,Male,8.00,0,0,No,children,Urban,84.68,14.5,Unknown,0
1126,Male,10.00,0,0,No,children,Rural,93.11,14.6,Unknown,0
740,Female,5.00,0,0,No,children,Urban,93.88,14.6,Unknown,0
4478,Male,8.00,0,0,No,children,Rural,108.06,14.6,Unknown,0

In [29]:
df.groupby(["gender","ever_married"]).agg({"avg_glucose_level":["min","max"]}).reset_index()

   gender ever_married avg_glucose_level
                                     min     max
0  Female           No             55.12  266.59
1  Female          Yes             55.27  267.76
2    Male           No             55.25  256.74
3    Male          Yes             55.22  271.74

In [34]:
df.groupby(["gender","ever_married"]).agg({"avg_glucose_level":["min","max"]}).reset_index()

   gender ever_married avg_glucose_level
                                     min     max
0  Female           No             55.12  266.59
1  Female          Yes             55.27  267.76
2    Male           No             55.25  256.74
3    Male          Yes             55.22  271.74

In [35]:
def fun(i):
    if i<=10:
        return "kid"
    elif i>10 and i<=20:
        return "teenager"
    else:
        return "adult"

In [42]:
df["age"]=df["age"].apply(fun)
df

,gender,age,hypertension,heart_disease,ever_married,work_type,Residence_type,avg_glucose_level,bmi,smoking_status,stroke
0,Male,adult,0,1,Yes,Private,Urban,228.69,36.6,formerly smoked,1
1,Male,adult,0,1,Yes,Private,Rural,105.92,32.5,never smoked,1
2,Female,adult,0,0,Yes,Private,Urban,171.23,34.4,smokes,1
3,Female,adult,1,0,Yes,Self-employed,Rural,174.12,24.0,never smoked,1
4,Male,adult,0,0,Yes,Private,Urban,186.21,29.0,formerly smoked,1
...,...,...,...,...,...,...,...,...,...,...,...
4976,Male,adult,0,0,No,Private,Rural,70.15,29.8,formerly smoked,0
4977,Male,adult,0,0,Yes,Private,Urban,191.15,31.1,smokes,0
4978,Female,adult,1,0,Yes,Govt_job,Rural,95.02,31.8,smokes,0
4979,Male,adult,0,0,Yes,Private,Rural,83.94,30.0,smokes,0
4980,Female,adult,1,0,Yes,Private,Urban,83.75,29.1,never smoked,0

In [44]:
df.groupby(["age"])["hypertension","avg_glucose_level","bmi"].agg(["min","max"]).reset_index()

<ipython-input-44-15e412a0b1ed>:1: FutureWarning: Indexing with multiple keys (implicitly converted to a tuple of keys) will be deprecated, use a list instead.
  df.groupby(["age"])["hypertension","avg_glucose_level","bmi"].agg(["min","max"]).reset_index()

        age hypertension     avg_glucose_level           bmi
                     min max               min     max   min   max
0     adult            0   1             55.12  271.74  14.1  48.9
1       kid            0   0             55.34  206.25  14.0  35.2
2  teenager            0   1             55.25  233.71  14.3  48.8

In [46]:
df.groupby(["age","gender"])["stroke"].count().reset_index()

        age  gender  stroke
0     adult  Female    2410
1     adult    Male    1583
2       kid  Female     226
3       kid    Male     267
4  teenager  Female     271
5  teenager    Male     224